
module.exports = {
  // files: [
  //   ["app.js", ""],
  //   ["app.json", ""],
  //   ["app.wxss", ""],
  //   ["assets", ""],
  //   ["build", ""],
  //   ["components", ""],
  //   ["config", ""],
  //   ["custom-tab-bar", ""],
  //   ["dist", ""],
  //   ["doc", ""],
  //   ["gulpfile.js", ""],
  //   ["images", ""],
  //   ["node_modules", ""],
  //   ["package-lock.json", ""],
  //   ["package.json", ""],
  //   ["packageDemos", ""],
  //   ["packageJourney", ""],
  //   ["packageMain", ""],
  //   ["packagePet", ""],
  //   ["packageScan", ""],
  //   ["pages", ""],
  //   ["pkgGuide", ""],
  //   ["project.config.json", ""],
  //   ["project.private.config.json", ""],
  //   ["remote", ""],
  //   ["service", ""],
  //   ["sitemap.json", ""],
  //   ["third", ""],
  //   ["tsconfig.json", ""],
  //   ["typings", ""],
  //   ["utils", ""],
  //   ["yarn-error.log", ""],
  //   ["yarn.lock", ""],
  // ]
}